### ISSUE TITLE
Wrong file gets shown in exception message when the file loaded by Polyglot raises a LoadError

### ISSUE THREAD

**Issue by jgarber** [cjheath/polyglot#1]
In Treetop, the .treetop files get eval'd.  If a require 'nonexistent_file' is inside the treetop file, it raises that but then gets caught, and the original exception is re-raised, which isn't true.  So, if foo.treetop contains "require 'nonexistent_file'", the error message says "no such file to load -- foo" even though it was able to find foo.treetop.

Cooking up a patch...

**Comment by jgarber** [comment]
Fixed in my branch.  Sent you a pull request.

**Comment by cjheath** [comment]
Fixed and released as 0.2.7, thanks.

**Comment by cjheath** [comment]
Fixed again, differently (activesupport conflict) and released as 0.2.8.
