### ISSUE TITLE
Ruby 1.9 issue: can't convert Pathname into String (TypeError)

### ISSUE THREAD

**Issue by grimen** [cjheath/polyglot#2]
Got a dependdency that depends on polyglot, but on Ruby 1.9.1 it fails with the classic:

<pre>
/Users/jonas/.ruby_versions/ruby-1.9.1-p129/bin/ruby -I"lib:test" "/Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake/rake_test_loader.rb" "test/unit/account_test.rb" "test/unit/profile_test.rb" 
/Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.8/lib/polyglot.rb:30:in `[]': can't convert Pathname into String (TypeError)
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.8/lib/polyglot.rb:30:in `block in find'
...
</pre>

Easily solved with Pathname#to_s before...

**Comment by cjheath** [comment]
Fixed in 0.2.9, released today.

**Comment by grimen** [comment]
Great! =)

**Comment by cjheath** [comment]
Unfortunately the versions of Ruby 1.9.1 and 1.9.2 that RVM installs are both faulty, failing in rb_define_method from ActiveSupport where it uses **send**. The bug is supposedly fixed, but the fix isn't yet available to RVM, and I'm still unwilling to manage multiple Ruby versions manually.

**Comment by grimen** [comment]
Is this the same with "ruby_switcher"? I started to use that before RVM, and didn't switch.

Now I get (I guess this is what u mean?):

<pre>
polyglot-0.2.9/lib/polyglot.rb:70:in `require': wrong number of arguments(2 for 1) (ArgumentError)
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
</pre>


But this should be possible to resolve with:

<pre>
def require(*args)
    polyglot_original_require(*args)
</pre>


...or? &block - if needed - should just the last param in *args. Should work, haven't tried.

**Comment by cjheath** [comment]
This error will only occur if _your code_ called require with two arguments. The addition of the block is _not_ a second argument, because it's preceded by &. Can you show me the code that called require?

**Comment by grimen** [comment]
I'm not requiring polyglot myself, Rails does this:

<pre>
c-80f6e255:starter_app jonas$ rake test
(in /Users/jonas/Development/projects/starter_app)
** [i18n:] Loaded locales: en
/Users/jonas/.ruby_versions/ruby-1.9.1-p129/bin/ruby -I"lib:test" "/Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake/rake_test_loader.rb" "test/unit/account_test.rb" "test/unit/profile_test.rb" 
/Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require': wrong number of arguments(2 for 1) (ArgumentError)
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:158:in `require'
    from /Users/jonas/Development/projects/starter_app/test/shoulda_macros/w3c_validation_macros.rb:3:in `<top (required)>'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:158:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/thoughtbot-shoulda-2.10.2/lib/shoulda/autoload_macros.rb:43:in `block in autoload_macros'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/thoughtbot-shoulda-2.10.2/lib/shoulda/autoload_macros.rb:42:in `each'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/thoughtbot-shoulda-2.10.2/lib/shoulda/autoload_macros.rb:42:in `autoload_macros'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/thoughtbot-shoulda-2.10.2/lib/shoulda/rails.rb:12:in `<top (required)>'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:158:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/thoughtbot-shoulda-2.10.2/lib/shoulda/test_unit.rb:9:in `<top (required)>'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:158:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/thoughtbot-shoulda-2.10.2/lib/shoulda.rb:8:in `<top (required)>'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:158:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rails-2.3.4/lib/rails/gem_dependency.rb:208:in `load'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rails-2.3.4/lib/initializer.rb:307:in `block in load_gems'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rails-2.3.4/lib/initializer.rb:307:in `each'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rails-2.3.4/lib/initializer.rb:307:in `load_gems'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rails-2.3.4/lib/initializer.rb:169:in `process'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rails-2.3.4/lib/initializer.rb:113:in `run'
    from /Users/jonas/Development/projects/starter_app/config/environment.rb:11:in `<top (required)>'
    from /Users/jonas/Development/projects/starter_app/test/test_helper.rb:3:in `require'
    from /Users/jonas/Development/projects/starter_app/test/test_helper.rb:3:in `<top (required)>'
    from /Users/jonas/Development/projects/starter_app/test/unit/account_test.rb:28:in `require'
    from /Users/jonas/Development/projects/starter_app/test/unit/account_test.rb:28:in `<top (required)>'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `load'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `block in <main>'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `each'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `<main>'
/Users/jonas/.ruby_versions/ruby-1.9.1-p129/bin/ruby -I"lib:test" "/Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake/rake_test_loader.rb" "test/functional/accounts_controller_test.rb" 
/Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require': wrong number of arguments(2 for 1) (ArgumentError)
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:158:in `require'
    from /Users/jonas/Development/projects/starter_app/test/shoulda_macros/w3c_validation_macros.rb:3:in `<top (required)>'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:158:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/thoughtbot-shoulda-2.10.2/lib/shoulda/autoload_macros.rb:43:in `block in autoload_macros'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/thoughtbot-shoulda-2.10.2/lib/shoulda/autoload_macros.rb:42:in `each'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/thoughtbot-shoulda-2.10.2/lib/shoulda/autoload_macros.rb:42:in `autoload_macros'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/thoughtbot-shoulda-2.10.2/lib/shoulda/rails.rb:12:in `<top (required)>'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:158:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/thoughtbot-shoulda-2.10.2/lib/shoulda/test_unit.rb:9:in `<top (required)>'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:158:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/thoughtbot-shoulda-2.10.2/lib/shoulda.rb:8:in `<top (required)>'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:158:in `require'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rails-2.3.4/lib/rails/gem_dependency.rb:208:in `load'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rails-2.3.4/lib/initializer.rb:307:in `block in load_gems'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rails-2.3.4/lib/initializer.rb:307:in `each'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rails-2.3.4/lib/initializer.rb:307:in `load_gems'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rails-2.3.4/lib/initializer.rb:169:in `process'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rails-2.3.4/lib/initializer.rb:113:in `run'
    from /Users/jonas/Development/projects/starter_app/config/environment.rb:11:in `<top (required)>'
    from /Users/jonas/Development/projects/starter_app/test/test_helper.rb:3:in `require'
    from /Users/jonas/Development/projects/starter_app/test/test_helper.rb:3:in `<top (required)>'
    from /Users/jonas/Development/projects/starter_app/test/functional/accounts_controller_test.rb:2:in `require'
    from /Users/jonas/Development/projects/starter_app/test/functional/accounts_controller_test.rb:2:in `<top (required)>'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `load'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `block in <main>'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `each'
    from /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `<main>'
/Users/jonas/.ruby_versions/ruby-1.9.1-p129/bin/ruby -I"lib:test" "/Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake/rake_test_loader.rb"  
Errors running test:units and test:functionals!
</pre>

**Comment by cjheath** [comment]
It's not the require of polyglot that's the problem, it's the shoulda_macros:
/Users/jonas/Development/projects/starter_app/test/shoulda_macros/w3c_validation_macros.rb:3
Show me this line of code; it has a require with two arguments.

Your argument about splatted-parameters and blocks is wrong, Ruby doesn't work like that. The &block parameter is not a parameter, and doesn't get included in a splat. Polyglot passes the original require _exactly_ the same parameters and block that it received itself, and in this case, that's wrong.

**Comment by grimen** [comment]
Oh, you are very right...didn't know that this was valid in Ruby 1.8.6/1.8.7 even:

<pre>
require 'w3c_validators', '>= 0.9.3'
</pre>


OK, false alarm then. Sorry for any confusion.

Regarding the args thing I noticed that I was totally wrong using some simple experiments in IRB, but thanks for correcting me on that. Lesson of the day.

Cheers

**Comment by reiz** [comment]
I have now the same issue with Ruby 2.0.0p0 :-/

**Comment by cjheath** [comment]
I haven't installed 2.0.0 yet. Can you raise a new issue, with an example please?

**Comment by reiz** [comment]
Problem solved. It was a problem with the linux right management.
