### ISSUE TITLE
0.3.2 gem includes website files (including GPL code)

### ISSUE THREAD

**Issue by jfirebaugh** [cjheath/polyglot#3]
It looks like the switch from Hoe to Jeweler led to to the `website` directory being included in the gem, which wasn't the case in 0.3.1. I'm guessing this was unintentional? Among other things, the website includes the GPL-licensed "curvyCorners" code, whose presence in an otherwise MIT-licensed gem causes lawyers to hem and haw.

**Comment by cjheath** [comment]
Oh, I see. Hem, haw, I suppose I'd better get rid of that then. Thanks for the alert.
