### ISSUE TITLE
iconv will be deprecated in the future, use String#encode instead.

### ISSUE THREAD

**Issue by victorbstan** [cjheath/polyglot#4]
gems/ruby-1.9.3-p194/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require': iconv will be deprecated in the future, use String#encode instead.

**Comment by cjheath** [comment]
This message comes from the original require, which polyglot wraps, not from polyglot itself. Polyglot has no dependency on iconv. Please look at your calling code.
