### ISSUE TITLE
Polyglot does not account for paths relative to the PWD

### ISSUE THREAD

**Issue by sarahzrf** [cjheath/polyglot#5]
That is to say, `require './foo'` will not check the current directory.

**Comment by cjheath** [comment]
This behaviour is correct. It should not check the current directory unless that's in $:

**Comment by sarahzrf** [comment]
That's how `Kernel#require` works though...

**Comment by cjheath** [comment]
Not any more, it isn't:
$ echo Foo > foo.rb
$ irb
~> Console extensions: wirble hirb ap rails2 rails3 pm interactive_editor

> > Kernel.require 'foo'
> > LoadError: cannot load such file -- foo
> >     from (irb):1:in `require'
> >     from (irb):1
> >     from /usr/bin/irb:16:in`<main>'

**Comment by cjheath** [comment]
By the way, you should stop using Ruby 1.8 - it's too old.

**Comment by sarahzrf** [comment]
Yes, I mean `require './foo'`, not `require 'foo'`. And I'm on 1.9 right now.

**Comment by cjheath** [comment]
Ok, I understand the issue now, verified using Treetop's Polyglot loader. Thanks for the report.

$ echo 'grammar Foo; end' > foo.tt
$ irb -rpolyglot -rtreetop
>> require 'foo'
(exception)

**Comment by cjheath** [comment]
Fixed and gem 0.3.4 released

**Comment by sarahzrf** [comment]
Thank you :)
