### ISSUE TITLE
Override `Kernel::load` as well as `Kernel::require`?

### ISSUE THREAD

**Issue by jimsynz** [cjheath/polyglot#7]
Hi there.

There are a bunch of libraries (most notably https://github.com/rspec/rspec-core) which use `Kernel::load` to load files, rather than `Kernel::require` - is there an easy way to work around this with Polyglot?

**Comment by cjheath** [comment]
It's not clear to me that Polyglot should get involved in Kernel::load. When I #load something, I've already found the thing I want to load. Can you make a lucid argument for it?

Perhaps Polyglot should expose a #load method that looks up its loaders for the specified file? But I don't think that overriding Kernel#load would be a good thing.

**Comment by jimsynz** [comment]
There are two examples that come to hand:
- implementing tests (such as specs) using another language that can be evaluated by Ruby
- implementing controllers, models, etc for Rails in another language.

Both of these require `Kernel::load` to understand how to load non-ruby code.

**Comment by cjheath** [comment]
One of the Rspec3 committers is in my immediate circles. I'll ask @jon_r, after I deal with some personal matters... unless you can come up with a firm suggestion?

**Comment by jimsynz** [comment]
I was going to ask @JonRowe about it yesterday, but forgot.  The problem is that RSpec already knows exactly which files it wants to load, so it's not sensible to use require in that circumstance.

Problem method is: https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/configuration.rb#L1104-L1107

**Comment by JonRowe** [comment]
The reason why RSpec uses `load` over `require`, is `require` won't reevaluate files, n multiple calls to `load` however will result in the file being evaulated n times. This is necessary for us to support environment pre loaders (like zeus, spork, spring) and test watchers (like guard, autotest) so that as your writing specs they keep being loaded.

FWIW `require` works with exact filename's just fine.

**Comment by cjheath** [comment]
JonRowe, that's well-understood. But for people using Polyglot to require non-Ruby files, load doesn't do that. I'm reluctant to hook load in all cases, and also reluctant to modify RSpec to know about Polyglot and choose a custom loader instead. So I'm in a bit of a quandary. Can you suggest a solution?

**Comment by JonRowe** [comment]
Have a ruby file that RSpec will load that uses the monkey patched require to load the other files.

**Comment by jimsynz** [comment]
@JonRowe turns out that that's a bit more tricky than I anticipated, but I'll take a look. Thanks @cjheath for the comments, I'll close this out here.

:+1:
