### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by alex-rodriguez** [cjheath/polyglot#8]
Hi, our application crashes on polyglot.rb line 65: [BUG] Segmentation fault at 0x00000000000000

I have Ubuntu 10.04.4 LTS, ruby 2.2.2p95 and Rails 4.2.5 installed. Please find attached a copy of the log file.

Best regards,

Alex

[polyglot_segmentation_fault.txt](https://github.com/cjheath/polyglot/files/210091/polyglot_segmentation_fault.txt)

**Comment by cjheath** [comment]
Line 65 is where polyglot calls the original require, usually Kernel#require. That is what is crashing, not polyglot.

**Comment by alex-rodriguez** [comment]
Thanks for your quick response, I knew it was not probable it were this gem's fault but had to ask in order to clear up some doubts. 

Best regards
