### ISSUE TITLE
Incompatibility with MRI 2.4

### ISSUE THREAD

**Issue by mightylucene** [cjheath/polyglot#9]
I got following error when upgrading ruby 2.4

`/Users/lokenmakwana/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': cannot load such file -- xmlrpc/client (LoadError)`

There are some games which are still in development and depends on it, eg. deface

**Comment by cjheath** [comment]
This is not a fault with polyglot. The xmlrpc/client cannot be loaded; that's why it got a LoadError.
